from datetime import UTC, datetime
from dataclasses import replace
import json
from pathlib import Path

import duckdb
import pytest
from fastapi.testclient import TestClient

from natsume_simple.api import create_app
from natsume_simple.artifact_builder import (
    ArtifactBuildError,
    ArtifactRecords,
    BuildMetadata,
    CollocationOccurrence,
    CorpusRecord,
    SentenceRecord,
    SourceDocument,
    build_artifact,
)


def fixture_records():
    corpora = [CorpusRecord("alpha", "Alpha"), CorpusRecord("beta", "Beta")]
    sources = [
        SourceDocument(
            corpus_id="alpha",
            external_id="a1",
            title="Alpha one",
            year=2024,
            author=None,
            publisher="Fixture",
            url=None,
            text_units=("情報を集める。",),
            content_sha256="a" * 64,
        ),
        SourceDocument(
            corpus_id="beta",
            external_id="b1",
            title="Beta one",
            year=2025,
            author=None,
            publisher="Fixture",
            url=None,
            text_units=("研究が進める。",),
            content_sha256="b" * 64,
        ),
    ]
    sentences = [
        SentenceRecord(("alpha", "a1"), 0, "情報を集める。"),
        SentenceRecord(("beta", "b1"), 0, "研究が進める。"),
    ]
    occurrences = [
        CollocationOccurrence(
            ("alpha", "a1"),
            0,
            "情報",
            "を",
            "集める",
            (0, 2),
            (2, 3),
            (3, 6),
            "fixture-extractor",
        ),
        CollocationOccurrence(
            ("beta", "b1"),
            0,
            "研究",
            "が",
            "進める",
            (0, 2),
            (2, 3),
            (3, 6),
            "fixture-extractor",
        ),
    ]
    return ArtifactRecords(
        corpora=tuple(corpora),
        sources=tuple(sources),
        sentences=tuple(sentences),
        occurrences=tuple(occurrences),
    )


def build_fixture(directory: Path, instance_id: str):
    return build_artifact(
        directory,
        records=fixture_records(),
        metadata=BuildMetadata(
            artifact_instance_id=instance_id,
            identity_inputs={
                "builderRevision": "fixture-builder",
                "executionProfile": {"backend": "cpu", "threads": 1},
            },
            built_at=datetime(2026, 8, 12, tzinfo=UTC),
            content_license="Synthetic fixture data.",
            attribution="Generated by the test suite.",
        ),
    )


def test_build_artifact_derives_serving_facts_and_layout(tmp_path: Path):
    artifact = build_fixture(tmp_path / "artifact-a", "fixture-a")

    assert sorted(path.name for path in artifact.iterdir()) == [
        "ATTRIBUTION.md",
        "LICENSE-CONTENT.txt",
        "corpus.duckdb",
        "manifest.json",
    ]
    manifest = json.loads((artifact / "manifest.json").read_text())
    assert manifest["artifactInstanceId"] == "fixture-a"
    assert manifest["schemaVersion"] == 1
    assert manifest["identityInputs"]["executionProfile"] == {
        "backend": "cpu",
        "threads": 1,
    }
    assert manifest["identityInputs"]["sources"] == [
        {
            "contentSha256": "a" * 64,
            "corpusId": "alpha",
            "externalId": "a1",
        },
        {
            "contentSha256": "b" * 64,
            "corpusId": "beta",
            "externalId": "b1",
        },
    ]
    assert manifest["relationCounts"] == {
        "corpus": 2,
        "source": 2,
        "sentence": 2,
        "collocationOccurrence": 2,
    }

    with duckdb.connect(str(artifact / "corpus.duckdb"), read_only=True) as conn:
        assert conn.execute(
            "SELECT * FROM corpus_stats ORDER BY corpus_id"
        ).fetchall() == [
            ("alpha", 1, 1, 1),
            ("beta", 1, 1, 1),
        ]
        assert conn.execute(
            "SELECT * FROM lemma_frequency ORDER BY part_of_speech, lemma"
        ).fetchall() == [
            ("noun", "情報", 1),
            ("noun", "研究", 1),
            ("verb", "進める", 1),
            ("verb", "集める", 1),
        ]

    with TestClient(create_app(artifact)) as client:
        assert client.get("/api/health/ready").json() == {
            "status": "ok",
            "databaseBuildId": "fixture-a",
            "schemaVersion": 1,
        }


def test_repeated_builds_keep_identity_inputs_and_relations(tmp_path: Path):
    first = build_fixture(tmp_path / "artifact-a", "fixture-a")
    second = build_fixture(tmp_path / "artifact-b", "fixture-b")

    first_manifest = json.loads((first / "manifest.json").read_text())
    second_manifest = json.loads((second / "manifest.json").read_text())
    assert first_manifest["artifactInstanceId"] != second_manifest["artifactInstanceId"]
    assert first_manifest["identityInputs"] == second_manifest["identityInputs"]

    tables = ["corpus", "source", "sentence", "collocation_occurrence"]
    with (
        duckdb.connect(str(first / "corpus.duckdb"), read_only=True) as first_db,
        duckdb.connect(str(second / "corpus.duckdb"), read_only=True) as second_db,
    ):
        for table in tables:
            first_rows = first_db.execute(
                f"SELECT * FROM {table} ORDER BY ALL"
            ).fetchall()
            second_rows = second_db.execute(
                f"SELECT * FROM {table} ORDER BY ALL"
            ).fetchall()
            assert first_rows == second_rows


def test_invalid_span_never_creates_a_publishable_artifact(tmp_path: Path):
    records = fixture_records()
    invalid = ArtifactRecords(
        corpora=records.corpora,
        sources=records.sources,
        sentences=records.sentences,
        occurrences=(replace(records.occurrences[0], verb_span=(3, 99)),),
    )
    output = tmp_path / "invalid"

    with pytest.raises(ArtifactBuildError, match="occurrence_span_invalid"):
        build_artifact(
            output,
            records=invalid,
            metadata=BuildMetadata(
                artifact_instance_id="invalid",
                identity_inputs={"builderRevision": "fixture"},
                built_at=datetime(2026, 8, 12, tzinfo=UTC),
                content_license="Synthetic fixture data.",
                attribution="Generated by the test suite.",
            ),
        )

    assert not output.exists()
    assert not output.with_name("invalid.staging").exists()
