name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACCELERATOR: 'cpu'

jobs:
  check:
    name: Build
    permissions:
      id-token: "write"
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Install frontend dependencies
        run: nix develop --command npm --prefix natsume-frontend ci
      - name: Run lint
        run: nix run .#lint
      - name: Run backend tests
        run: nix run .#run-tests
      - name: Check frontend
        run: nix run .#frontend-check
